FORMAT: 1A

# terraform-state-server

## State [/state]

This is a reverse-engineered definition of the Terraform state protocol based on the [http backend documentation](https://www.terraform.io/docs/backends/types/http.html) and experimentation with the terraform cli. It seems to work, but there may be missing/incorrect spots.

### Get State [GET]

Retrieve state

+ Response 200

+ Response 404

### Create or Update State [POST /state{?ID}]

Create or update state with optional locking (include the ID parameter for locking)

+ Parameters
    + ID: true (optional) - lock id returned by `LOCK /state`
        + default: false

+ Response 200

+ Response 400 (text/plain)

        state is not locked, but you included a lock id in your request

+ Response 423 (application/json)

        {
            "ID: "3b4feffc-e1f0-d242-68ab-81714a1336b0",
            "Operation: "OperationTypePlan",
            "Info: "",
            "Who: "johndoe@example.net",
            "Version: "0.10.5",
            "Created: "2017-09-17T17:41:10.59651162Z",
            "Path": ""
        }

### Create Lock [LOCK]

Lock the state and prevent anyone else from making changes until it's unlocked. You'll need to present the ID parameter when calling POST

+ Request (application/json)

        {
            "ID: "3b4feffc-e1f0-d242-68ab-81714a1336b0",
            "Operation: "OperationTypePlan",
            "Info: "",
            "Who: "johndoe@example.net",
            "Version: "0.10.5",
            "Created: "2017-09-17T17:41:10.59651162Z",
            "Path": ""
        }

+ Response 200

+ Response 409 (application/json)

        {
            "ID: "3b4feffc-e1f0-d242-68ab-81714a1336b0",
            "Operation: "OperationTypePlan",
            "Info: "",
            "Who: "johndoe@example.net",
            "Version: "0.10.5",
            "Created: "2017-09-17T17:41:10.59651162Z",
            "Path": ""
        }

### Release Lock [UNLOCK /state{?force}]

Release the lock so that others may make changes. You'll need to supply, at a minimum, the lock ID that you're holding.

+ Parameters
    + force (optional) - use to unlock in event that no one owns the lock any more. Could happen if something goes very wrong when terraform is running. USE WITH CARE

+ Request (application/json)

        {
            "ID: "3b4feffc-e1f0-d242-68ab-81714a1336b0",
            "Operation: "OperationTypePlan",
            "Info: "",
            "Who: "johndoe@example.net",
            "Version: "0.10.5",
            "Created: "2017-09-17T17:41:10.59651162Z",
            "Path": ""
        }

+ Response 200

+ Response 409 (text/plain)

        Not Locked

+ Response 423 (application/json)

        {
            "ID: "3b4feffc-e1f0-d242-68ab-81714a1336b0",
            "Operation: "OperationTypePlan",
            "Info: "",
            "Who: "johndoe@example.net",
            "Version: "0.10.5",
            "Created: "2017-09-17T17:41:10.59651162Z",
            "Path": ""
        }

### Purge [DELETE /state{?force}]

Delete all state and start over

+ Parameters
    + force (optional) - ignores the lock check for cases where you definitely want to purge (e.g. if a lock is stuck and you really don't care about your state). USE WITH CARE

+ Response 200

## Operations [/ping]

### Send Ping [GET]

Simple endpoint for proving the service is turned on.

+ Response 200 (application/json)

        {
            "pong": true
        }
